#!/bin/sh
# shellcheck disable=1090,1091

# system one time tasks

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /etc/runit/functions

msg "Welcome to Gentoo!"

[ -r /etc/runit.conf ] && . /etc/runit.conf

for f in /etc/runit/core-services/*.sh; do
    [ -r "$f" ] && . "$f"
done

mkdir -p /run/runit
install --mode=100 /dev/null /run/runit/stopit

msg "Initialization complete, running stage 2..."
