#!/bin/sh
exec >/dev/console 2>&1
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /etc/runit/functions

[ -r /etc/runit.conf ] && . /etc/runit.conf

if [ -e /run/runit/reboot ]; then
    chmod 100 /run/runit/reboot
fi

msg 'Waiting for services to stop...'
sv force-stop /var/service/*
sv exit /var/service/*

msg "Saving random seed..."
(
    umask 077
    bytes=$(cat /proc/sys/kernel/random/poolsize) || bytes=512
    dd if=/dev/urandom of=/var/lib/init/random-seed count=1 bs="$bytes" > /dev/null 2>&1
)

msg "Syncing hardware clock..."
if [ -n "$HARDWARECLOCK" ]; then
    hwclock --systohc ${HARDWARECLOCK:+--$(echo $HARDWARECLOCK | tr '[:upper:]' '[:lower:]')}
fi

msg "Stopping udev..."
udevadm control --exit

msg "Unmounting filesystems..."
umount -a -r

msg "Remounting rootfs read-only..."
mount -o remount,ro /

sync
