#!/bin/sh

msg() {
    # bold
    printf "\033[1m=> %s\033[m\n" "$@"
}

msg_ok() {
    # bold/green
    printf "\033[1m\033[32m OK\033[m\n"
}

msg_error() {
    # bold/red
    printf "\033[1m\033[31mERROR: %s\033[m\n" "$@"
}

msg_warn() {
    # bold/yellow
    printf "\033[1m\033[33mWARNING: %s\033[m\n" "$@"
}

sos() {
    echo
    echo "Cannot continue due to errors above, starting emergency shell."
    echo "When ready type exit to continue booting."
    /bin/sh -l
}

mnt() {
    mountpoint -q "$2" || mount "$@"
}
